### ISSUE TITLE
Clickup editor error

### ISSUE THREAD

**Issue by d0p3fish** [sternth/no-gender#1]
Actually im writing an documentation in Clickup Wiki.
When im writing the word "In", anywhere in the Text, the cursor jumps to the start of the line.

**Comment by sternth** [comment]
Thanks for opening this issue.
I only could reproduce this issue with HTMLElements with attribute contenteditable. This should be fixed with version 1.6.
When version 1.6 has been published can you please verify the issue doesn't exist anymore and reply it here.
Thank you!

**Comment by d0p3fish** [comment]
Thanks, seems to work now
